application/models.py
from application.extension import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True)
    email = db.Column(db.String(120), unique=True)
    password = db.Column(db.String(120))
    gender = db.Column(db.Integer, default=0)

    def __init__(self, username, gender, email, password):
        self.username = username
        self.email = email
        self.password = password
        self.gender = gender


    def __repr__(self):
        return '<User %r>' % self.username

application/__init__.py
from flask import Flask
from application.views.user import user_page
from application.extension import db
import os
import click
from application.models import User
from werkzeug.security import generate_password_hash


def create_app(config_name=None):
    if config_name is None:
        config_name = os.getenv('FLASK_CONFIG', 'development')

    app = Flask('application')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('SQLALCHEMY_DATABASE_URI')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.secret_key = "lalskskskskksksjsj"

    register_extensions(app)
    register_blueprints(app)
    register_commands(app)

    return app


def register_extensions(app):
    db.init_app(app)

def register_blueprints(app):
    app.register_blueprint(user_page)

def register_commands(app):
    @app.cli.command()
    def forge():
        """Generate fake data."""
        db.drop_all()
        db.create_all()

        hash_password = generate_password_hash('123456')
        user = User(username="admin", gender=0, email="admin@admin.com", password=hash_password)
        user1 = User(username="123455", gender=1, email="admin234@admin.com", password=hash_password)

        db.session.add(user)
        db.session.add(user1)
        db.session.commit()
        click.echo('Done.')

application/views/user.py
# encoding: utf8

from flask import Blueprint, render_template, session, redirect, request, url_for, flash
from application.models import User
from application.extension import db
from werkzeug.security import check_password_hash


user_page = Blueprint('user_page', __name__)


@user_page.route('/users')
def users():
    if session.get('user_id'):
        users = User.query.all()
        return render_template('user/index.html', users=users)
    else:
        return redirect('/')


@user_page.route('/')
@user_page.route('/login', methods=['GET', 'PoSt'])
def login():
    if request.method == 'GET':
        return render_template('user/login.html')
    else:
        name = request.form.get('name')
        pwd = request.form.get('password')

        user = User.query.filter(User.username == name).first()

        if user and check_password_hash(user.password, pwd):
            session['user_id'] = user.id
            # return redirect(url_for('user_page.users'))
            return '1'
        else:
            flash('登陆失败')
            # return render_template('user/login.html')
            return '0'


@user_page.route('/users/<id>', methods=['GET', 'Post'])
def edit(id):
    user = User.query.get(id)

    if request.method == 'GET':
        return render_template('user/edit.html', user=user)
    else:
        username = request.form.get('username')
        password = request.form.get('password')
        gender = request.form.get('gender')

        user.username = username
        user.password = password
        user.gender = gender

        db.session.commit()
        flash('修改成功')

        return redirect('/users')

application/templates/user/edit.html
<html>
<head>
    <style>
        .alert {
            color: red;
            text-align: center;
        }
    </style>

    <script src="/static/js/jQuery.min.js"></script>

</head>
<body>
<h1>Edit User</h1>
     {% for message in get_flashed_messages() %}
         <div class="alert">{{ message }}</div>
     {% endfor %}
    <form action="{{ url_for('user_page.edit', id=user.id) }}" method="post">
        <table>
            <tr><td>用户名：</td><td><input id="name" type="text" name="username" value="{{ user.username }}" /></td></tr>
            <tr><td>Email：</td><td><input id="email" type="text" name="email" value="{{ user.email }}" /></td>
            <tr><td>性别：</td>
                <td>
                    <input type="radio" name="gender" value="0" {% if user.gender == 0 %} checked {% endif %} />男
                    <input type="radio" name="gender" value="1" {% if user.gender == 1 %} checked {% endif %}/>女
                </td>
            <tr><td>&nbsp;</td><td><input id="submit" type="submit" name="submit" value="修改" /></td></tr>
        </table>
    </form>


</body>
</html>

application/templates/user/index.html
<html>
<head></head>
<body>

<h1>User List</h1>

<table>
    <tr>
        <td>username</td>
        <td>email</td>
        <td>操作</td>
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.username }}</td>
        <td>{{ user.email }}</td>
        <td><a href="{{url_for('user_page.edit', id=user.id)}}">修改</a></td>
    </tr>
    {% endfor %}
</table>

</body>
</html>

application/templates/user/login.html
<html>
<head>
    <style>
        .alert {
            color: red;
            text-align: center;
        }
    </style>

    <script src="/static/js/jQuery.min.js"></script>


</head>
<body>
<h1>Login</h1>
     {% for message in get_flashed_messages() %}
         <div class="alert">{{ message }}</div>
     {% endfor %}
    <form action="{{ url_for('user_page.login') }}" method="post">
        <table>
            <tr><td>用户名：</td><td><input id="name" type="text" name="name" /></td></tr>
            <tr><td>密码：</td><td><input id="password" type="password" name="password" /></td>

        </table>
    </form>

    <tr><td>&nbsp;</td><td><input id="submit" type="button" name="submit" value="Submit" /></td></tr>


<div id="qrcode"></div>
<script type="text/javascript">

function utf16to8(str) {
    var out, i, len, c;
    out = "";
    len = str.length;
    for(i = 0; i < len; i++) {
    c = str.charCodeAt(i);
    if ((c >= 0x0001) && (c <= 0x007F)) {
        out += str.charAt(i);
    } else if (c > 0x07FF) {
        out += String.fromCharCode(0xE0 | ((c >> 12) & 0x0F));
        out += String.fromCharCode(0x80 | ((c >>  6) & 0x3F));
        out += String.fromCharCode(0x80 | ((c >>  0) & 0x3F));
    } else {
        out += String.fromCharCode(0xC0 | ((c >>  6) & 0x1F));
        out += String.fromCharCode(0x80 | ((c >>  0) & 0x3F));
    }
    }
    return out;
}
</script>


<script>
    $(function(){
        $('#submit').click(function() {
            var name = $('#name').val();
            var password = $('#password').val();

            $.ajax({
                url: '/login',
                method: 'POST',
                data: {name: name, password: password},
                success: function(response) {
                    if(response == '1'){
                      alert('登录成功');
                      window.location.href = '/users';
                    }else{
                      alert('登录失败');
                    }
                }
            })
        });
    });
</script>

</body>
</html>